[package]
name = "ratatecs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy_app = "0.15.0"
bevy_ecs = "0.15.0"
bevy_state = "0.15.0"
crossterm = "0.28.1"
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }
